
[font]
size = 10.5

[font.bold]
family = "FantasqueSansM Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FantasqueSansM Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FantasqueSansM Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FantasqueSansM Nerd Font Mono"
style = "Regular"

[env]
TERM = "xterm-256color"

[general]
import = ["./theme.toml"]

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"
